name: parabricks_fq2bam
owner: bgruening
description: "Run GPU-bwa mem to convert FASTQ to BAM"
homepage_url: https://github.com/bgruening/galaxytools
long_description: 
    Run GPU-bwa mem to convert FASTQ to BAM
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/parabricks_fq2bam
type: unrestricted
categories:
- Mapping