name: cleanlab_issue_handler
owner: bgruening
description: Tool for detecting and handling data issues using Cleanlab.
long_description: >
  This tool uses Cleanlab to identify data issues such as label errors,
  outliers, near-duplicates, and non-IID samples in datasets for classification
  and regression tasks.

homepage_url: https://github.com/cleanlab/cleanlab
remote_repository_url: https://github.com/mjoudy/galaxy-cleanlab
type: unrestricted

categories:
  - Machine Learning
  - Data Cleaning
