name: llm_hub
owner: bgruening
description: LiteLLM - Call all LLM APIs using the OpenAI format.
long_description: |
  This tool provides a unified interface to interact with various LLM APIs using the OpenAI API format.
  It allows users to seamlessly switch between different LLM providers while maintaining compatibility with the OpenAI API.
  Users can specify the model, provide context, and ask a question.
  The tool will then generate and return the corresponding text based on the input provided.
remote_repository_url: https://github.com/bgruening/galaxytools/tree/master/tools/llm_hub
homepage_url: https://github.com/bgruening/galaxytools/tree/master/tools/llm_hub
type:
categories:
  - Machine Learning
maintainers:
  - arash77
